// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function CloseWindow():Promise<void>;

export function GetConfigSummary():Promise<main.DesktopConfigSummary>;

export function GetDesktopStatus():Promise<main.DesktopStatus>;

export function GetRuntimeSummary():Promise<main.DesktopRuntimeSummary>;

export function GetVersion():Promise<string>;

export function GetWindowState():Promise<main.DesktopWindowState>;

export function HideToTray():Promise<void>;

export function IsQuitting():Promise<boolean>;

export function MinimiseWindow():Promise<void>;

export function OpenAdminInBrowser():Promise<void>;

export function RestoreLastRoute():Promise<string>;

export function RunSelfCheck():Promise<main.DesktopSelfCheck>;

export function SaveWindowState(arg1:main.DesktopWindowState):Promise<main.DesktopWindowState>;

export function SendNativeNotice(arg1:string,arg2:string):Promise<void>;

export function ShowMainWindow():Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleMaximiseWindow():Promise<void>;
