// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['DesktopApp']['CloseWindow']();
}

export function GetConfigSummary() {
  return window['go']['main']['DesktopApp']['GetConfigSummary']();
}

export function GetDesktopStatus() {
  return window['go']['main']['DesktopApp']['GetDesktopStatus']();
}

export function GetRuntimeSummary() {
  return window['go']['main']['DesktopApp']['GetRuntimeSummary']();
}

export function GetVersion() {
  return window['go']['main']['DesktopApp']['GetVersion']();
}

export function GetWindowState() {
  return window['go']['main']['DesktopApp']['GetWindowState']();
}

export function HideToTray() {
  return window['go']['main']['DesktopApp']['HideToTray']();
}

export function MinimiseWindow() {
  return window['go']['main']['DesktopApp']['MinimiseWindow']();
}

export function OpenAdminInBrowser() {
  return window['go']['main']['DesktopApp']['OpenAdminInBrowser']();
}

export function RestoreLastRoute() {
  return window['go']['main']['DesktopApp']['RestoreLastRoute']();
}

export function RunSelfCheck() {
  return window['go']['main']['DesktopApp']['RunSelfCheck']();
}

export function SaveWindowState(arg1) {
  return window['go']['main']['DesktopApp']['SaveWindowState'](arg1);
}

export function SendNativeNotice(arg1, arg2) {
  return window['go']['main']['DesktopApp']['SendNativeNotice'](arg1, arg2);
}

export function ShowMainWindow() {
  return window['go']['main']['DesktopApp']['ShowMainWindow']();
}

export function Startup(arg1) {
  return window['go']['main']['DesktopApp']['Startup'](arg1);
}

export function ToggleMaximiseWindow() {
  return window['go']['main']['DesktopApp']['ToggleMaximiseWindow']();
}
